Repository ErikReider/SwayNotificationCenter, pull requests merged in 2022-05, with the labels that each got.

#117 Fixed markup parsing unofficial tags
  src/notiDaemon/notiDaemon.vala
  src/notification/notification.vala
Labels: bug

#118 Vala lint fixes + linting Github Action
  .github/workflows/linting.yml
  .uncrustify.cfg
  .vala-lint.conf
  src/ccDaemon/ccDaemon.vala
  src/client.vala
  src/configModel/configModel.vala
  src/constants.vala.in
  src/controlCenter/controlCenter.vala
  src/functions.vala
  src/main.vala
  src/notiDaemon/notiDaemon.vala
  src/notiModel/notiModel.vala
  src/notiWindow/notiWindow.vala
  src/notification/notification.vala
Labels: enhancement

#37 Ellipsize and wrap notification body
  src/notiWindow/notiWindow.ui
  src/notiWindow/notiWindow.vala
  src/notification/notification.vala
Labels: enhancement, help wanted

#119 Cache DND
  README.md
  src/cacher/cacher.vala
  src/controlCenter/controlCenter.vala
  src/meson.build
  src/notiDaemon/notiDaemon.vala
  src/swayncDaemon/swayncDaemon.vala
Labels: enhancement

#121 Do not keep transient notifications in the CC
  src/notiDaemon/notiDaemon.vala
  src/notiModel/notiModel.vala
Labels: enhancement

#123 Added GetSubscribeData to dbus daemon
  src/client.vala
  src/swayncDaemon/swayncDaemon.vala
Labels: enhancement
