Repository ErikReider/SwayNotificationCenter, pull requests merged in 2023-05, with the labels that each got.

#253 Fixed mpDris2 mpris issues
  src/controlCenter/widgets/mpris/interfaces.vala
  src/controlCenter/widgets/mpris/mpris_player.vala
Labels: bug

#258 Preserve config object item order
  src/configModel/configModel.vala
  src/controlCenter/widgets/baseWidget.vala
  src/meson.build
  src/notiDaemon/notiDaemon.vala
  src/orderedHashTable/orderedHashTable.vala
Labels: bug

#259 Add positonY center for notifications and CC
  src/configModel/configModel.vala
  src/configSchema.json
  src/controlCenter/controlCenter.vala
  src/notificationWindow/notificationWindow.vala
Labels: enhancement

#260 Added ability to toggle parsing of notification 2fa codes
  src/config.json.in
  src/configModel/configModel.vala
  src/configSchema.json
  src/notification/notification.vala
Labels: enhancement

#261 Added ability to choose wether layer-shell should be used or not
  src/config.json.in
  src/configModel/configModel.vala
  src/configSchema.json
  src/controlCenter/controlCenter.vala
  src/notificationWindow/notificationWindow.vala
  src/swayncDaemon/swayncDaemon.vala
Labels: enhancement

#263 Added control-center layer config option
  src/blankWindow/blankWindow.vala
  src/config.json.in
  src/configModel/configModel.vala
  src/configSchema.json
  src/controlCenter/controlCenter.vala
  src/notificationWindow/notificationWindow.vala
Labels: bug, enhancement

#264 Update swaync.5.scd #249
  man/swaync.5.scd
Labels: documentation
